apiVersion: v1
kind: Service
metadata:
  name: hello-world-serivce
  namespace: argocd

spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort:  30001
  selector:
    app: hello-world
