apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: hello-world-UI
  labels:
    app: hello-world
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: hello-world
