apiVersion: v1
kind: Service
metadata:
  name: hello-world-blue
  namespace: argocd
  labels:
    name: hello-world-blue

spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80

  selector:
    app: hello-world-blue


---

apiVersion: v1
kind: Service
metadata:
  name: hello-world-green
  namespace: argocd
  labels:
    name: hello-world-green

spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80

  selector:
    app: hello-world-green