apiVersion: v1
kind: Service
metadata:
  name: hello-world-blue
  namespace: argocd
  labels:
    app: hello-world
    color: blue

spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30030

  selector:
    app: hello-world
    color: blue


---

apiVersion: v1
kind: Service
metadata:
  name: hello-world-green
  namespace: argocd
  labels:
    app: hello-world
    color: green

spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30033

  selector:
    app: hello-world
    color: green